// biogenome-client/src/components/cms/dashboard/DeleteRequestsModule.vue
<template>
   <section aria-labelledby="delete-requests-module-title">
      <CmsCard
         title="Deletion Requests"
         description="Pending organism deletion requests from curators. Approving permanently removes the organism."
         icon="fa-trash-can"
         color="danger"
         :loading="isLoading"
      >
         <!-- Badge count in header -->
         <template v-if="total > 0" #actions>
            <span class="cms-count-badge">{{ total }}</span>
         </template>

         <!-- Filters -->
         <template #filters>
            <CmsSearchInput
               v-model="filter"
               field-name="cms-delete-requests-filter"
               placeholder="Filter by name or taxid…"
               @update:model-value="debouncedFetch"
            />
         </template>

         <!-- Table -->
         <template v-if="!isLoading">
            <DashboardEmptyState
               v-if="items.length === 0"
               icon="fa-circle-check"
               title="No pending requests"
               description="All organism deletion requests have been resolved."
            />

            <table v-else class="cms-table" role="grid">
               <thead>
                  <tr class="cms-table__head-row">
                     <th class="cms-table__th">Species</th>
                     <th class="cms-table__th">TaxID</th>
                     <th class="cms-table__th cms-table__th--right">Actions</th>
                  </tr>
               </thead>
               <tbody>
                  <tr
                     v-for="item in items"
                     :key="item.taxid"
                     class="cms-table__row"
                  >
                     <td class="cms-table__td">
                        <span class="cms-table__sci-name">{{ item.scientific_name }}</span>
                     </td>
                     <td class="cms-table__td cms-table__td--mono">{{ item.taxid }}</td>
                     <td class="cms-table__td cms-table__td--right">
                        <div class="cms-table__actions">
                           <CmsBtn
                              icon="fa-xmark"
                              variant="warning"
                              :disabled="!!processingTaxid"
                              :loading="processingTaxid === item.taxid && processingAction === 'deny'"
                              @click="handleDeny(item.taxid)"
                           >
                              Deny
                           </CmsBtn>
                           <CmsBtn
                              icon="fa-trash"
                              variant="danger"
                              :disabled="!!processingTaxid"
                              :loading="processingTaxid === item.taxid && processingAction === 'approve'"
                              @click="promptApprove(item)"
                           >
                              Delete
                           </CmsBtn>
                        </div>
                     </td>
                  </tr>
               </tbody>
            </table>
         </template>

         <!-- Pagination -->
         <template v-if="!isLoading && total > limit" #footer>
            <CmsPagination
               v-model="currentPage"
               :total="total"
               :page-size="limit"
               @update:model-value="fetchData"
            />
         </template>
      </CmsCard>

      <CmsModal v-model="showApproveModal">
         <template #header="{ titleId }">
            <h3 :id="titleId" class="cms-delete-req-modal__title">Approve deletion request</h3>
         </template>
         <p>
            This will permanently delete
            <em>{{ pendingApproveItem?.scientific_name }}</em>
            and all related data. This action is irreversible.
         </p>
         <template #footer>
            <CmsBtn variant="secondary" @click="showApproveModal = false">Cancel</CmsBtn>
            <CmsBtn
               variant="danger"
               :loading="processingTaxid === pendingApproveItem?.taxid"
               @click="confirmApprove"
            >
               Delete organism
            </CmsBtn>
         </template>
      </CmsModal>
   </section>
</template>

<script setup lang="ts">
   import { onMounted, ref } from 'vue'
   import { useToast } from 'vuestic-ui'
   import { AxiosError } from 'axios'
   import AuthService from '../../../services/AuthService'
   import CommonService from '../../../services/CommonService'
   import CmsCard from './CmsCard.vue'
   import CmsBtn from '../ui/CmsBtn.vue'
   import CmsSearchInput from './CmsSearchInput.vue'
   import CmsPagination from './CmsPagination.vue'
   import DashboardEmptyState from './DashboardEmptyState.vue'
   import CmsModal from '../ui/CmsModal.vue'

   const { init } = useToast()

   const items = ref<Record<string, any>[]>([])
   const total = ref(0)
   const isLoading = ref(false)
   const filter = ref('')
   const currentPage = ref(1)
   const limit = 7

   const processingTaxid = ref<string | null>(null)
   const processingAction = ref<'approve' | 'deny' | null>(null)
   const showApproveModal = ref(false)
   const pendingApproveItem = ref<Record<string, any> | null>(null)

   function debounce<T extends (...args: any[]) => void>(fn: T, ms = 350) {
      let timer: ReturnType<typeof setTimeout>
      return (...args: Parameters<T>) => {
         clearTimeout(timer)
         timer = setTimeout(() => fn(...args), ms)
      }
   }

   async function fetchData() {
      isLoading.value = true
      try {
         const { data } = await CommonService.getItems('organisms', {
            pending_deletion: true,
            filter: filter.value,
            limit,
            offset: (currentPage.value - 1) * limit,
         })
         items.value = data.data ?? []
         total.value = data.total ?? 0
      } catch {
         items.value = []
      } finally {
         isLoading.value = false
      }
   }

   const debouncedFetch = debounce(() => {
      currentPage.value = 1
      fetchData()
   })

   function promptApprove(item: Record<string, any>) {
      pendingApproveItem.value = item
      showApproveModal.value = true
   }

   async function confirmApprove() {
      if (!pendingApproveItem.value) return
      const taxid = pendingApproveItem.value.taxid
      processingTaxid.value = taxid
      processingAction.value = 'approve'
      try {
         await AuthService.deleteItem('organisms', taxid)
         init({ message: `${pendingApproveItem.value.scientific_name} deleted.`, color: 'success' })
         showApproveModal.value = false
         currentPage.value = 1
         await fetchData()
      } catch (err) {
         const ax = err as AxiosError
         init({ message: (ax.response?.data as string) ?? 'Deletion failed.', color: 'danger' })
      } finally {
         processingTaxid.value = null
         processingAction.value = null
      }
   }

   async function handleDeny(taxid: string) {
      processingTaxid.value = taxid
      processingAction.value = 'deny'
      try {
         await AuthService.deleteOrganismsToDeleteRequest(taxid)
         init({ message: 'Request denied.', color: 'success' })
         await fetchData()
      } catch (err) {
         const ax = err as AxiosError
         init({ message: (ax.response?.data as string) ?? 'Failed to deny request.', color: 'danger' })
      } finally {
         processingTaxid.value = null
         processingAction.value = null
      }
   }

   onMounted(fetchData)
</script>

<style lang="scss" scoped>
   .cms-delete-req-modal__title {
      margin: 0;
      font-size: 1rem;
      font-weight: 600;
      line-height: 1.35;
      color: var(--cms-danger);
   }
</style>

// front/components/cms/dashboard/delete-requests-module.tsx
'use client'

import { useCallback, useEffect, useState } from 'react'
import { Loader2 } from 'lucide-react'
import { toast } from 'sonner'

import {
   AlertDialog,
   AlertDialogAction,
   AlertDialogCancel,
   AlertDialogContent,
   AlertDialogDescription,
   AlertDialogFooter,
   AlertDialogHeader,
   AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import {
   Table,
   TableBody,
   TableCell,
   TableHead,
   TableHeader,
   TableRow,
} from '@/components/ui/table'
import { extractApiMessage } from '@/lib/cms/extract-api-message'
import { DashboardModuleHeader } from '@/components/cms/dashboard/dashboard-module-header'
import { DashboardModulePagination } from '@/components/cms/dashboard/dashboard-module-pagination'
import { cmsDeleteDeletionRequest, cmsDeleteItem, cmsGetItems } from '@/lib/cms/services/auth'

const LIMIT = 7

export function DeleteRequestsModule() {
   const [items, setItems] = useState<Record<string, unknown>[]>([])
   const [total, setTotal] = useState(0)
   const [loading, setLoading] = useState(true)
   const [filterDraft, setFilterDraft] = useState('')
   const [filter, setFilter] = useState('')
   const [page, setPage] = useState(1)
   const [processing, setProcessing] = useState<string | null>(null)
   const [approveItem, setApproveItem] = useState<Record<string, unknown> | null>(null)

   useEffect(() => {
      const t = setTimeout(() => {
         setFilter(filterDraft)
         setPage(1)
      }, 350)
      return () => clearTimeout(t)
   }, [filterDraft])

   const fetchData = useCallback(async () => {
      setLoading(true)
      try {
         const { data, total: t } = await cmsGetItems('organisms', {
            pending_deletion: true,
            filter,
            limit: LIMIT,
            offset: (page - 1) * LIMIT,
         })
         if ((data?.length ?? 0) === 0 && page > 1 && (t ?? 0) > 0) {
            setPage((p) => Math.max(1, p - 1))
            return
         }
         setItems(data ?? [])
         setTotal(t ?? 0)
      } catch {
         setItems([])
         setTotal(0)
      } finally {
         setLoading(false)
      }
   }, [filter, page])

   useEffect(() => {
      void fetchData()
   }, [fetchData])

   async function handleDeny(taxid: string) {
      setProcessing(taxid)
      try {
         await cmsDeleteDeletionRequest(taxid)
         toast.success('Request denied.')
         await fetchData()
      } catch (e) {
         toast.error(extractApiMessage(e, 'Failed to deny'))
      } finally {
         setProcessing(null)
      }
   }

   async function confirmApprove() {
      if (!approveItem?.taxid) return
      const taxid = String(approveItem.taxid)
      setProcessing(taxid)
      try {
         await cmsDeleteItem('organisms', taxid)
         toast.success('Organism deleted.')
         setApproveItem(null)
         await fetchData()
      } catch (e) {
         toast.error(extractApiMessage(e, 'Deletion failed'))
      } finally {
         setProcessing(null)
      }
   }

   return (
      <>
         <Card className="gap-3 border-destructive/20 shadow-sm">
            <DashboardModuleHeader
               description="Approve or deny curator deletion requests."
               badge={
                  total > 0 ? (
                     <span className="rounded-full bg-destructive px-2 py-0.5 text-xs font-bold text-destructive-foreground">
                        {total}
                     </span>
                  ) : null
               }
            />
            <CardContent className="space-y-4">
               <Input
                  placeholder="Filter by name or taxid…"
                  value={filterDraft}
                  onChange={(e) => setFilterDraft(e.target.value)}
                  className="max-w-md"
               />
               {loading ? (
                  <div className="flex justify-center py-10">
                     <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
                  </div>
               ) : items.length === 0 ? (
                  <p className="py-8 text-center text-sm text-muted-foreground">No pending requests.</p>
               ) : (
                  <div className="rounded-md border border-border">
                     <Table>
                        <TableHeader>
                           <TableRow>
                              <TableHead>Species</TableHead>
                              <TableHead>Taxid</TableHead>
                              <TableHead className="text-right">Actions</TableHead>
                           </TableRow>
                        </TableHeader>
                        <TableBody>
                           {items.map((item) => (
                              <TableRow key={String(item.taxid)}>
                                 <TableCell className="italic">{String(item.scientific_name)}</TableCell>
                                 <TableCell className="font-mono text-sm">{String(item.taxid)}</TableCell>
                                 <TableCell className="text-right">
                                    <div className="flex justify-end gap-2">
                                       <Button
                                          variant="outline"
                                          size="sm"
                                          disabled={!!processing}
                                          onClick={() => void handleDeny(String(item.taxid))}
                                       >
                                          {processing === item.taxid ? (
                                             <Loader2 className="h-4 w-4 animate-spin" />
                                          ) : (
                                             'Deny'
                                          )}
                                       </Button>
                                       <Button
                                          variant="destructive"
                                          size="sm"
                                          disabled={!!processing}
                                          onClick={() => setApproveItem(item)}
                                       >
                                          Delete
                                       </Button>
                                    </div>
                                 </TableCell>
                              </TableRow>
                           ))}
                        </TableBody>
                     </Table>
                  </div>
               )}
               {total > LIMIT ? (
                  <DashboardModulePagination
                     page={page}
                     totalPages={Math.ceil(total / LIMIT)}
                     onPrevious={() => setPage((p) => p - 1)}
                     onNext={() => setPage((p) => p + 1)}
                  />
               ) : null}
            </CardContent>
         </Card>

         <AlertDialog open={!!approveItem} onOpenChange={() => setApproveItem(null)}>
            <AlertDialogContent>
               <AlertDialogHeader>
                  <AlertDialogTitle>Approve deletion?</AlertDialogTitle>
                  <AlertDialogDescription>
                     Permanently delete <em>{approveItem ? String(approveItem.scientific_name) : ''}</em> and
                     related data.
                  </AlertDialogDescription>
               </AlertDialogHeader>
               <AlertDialogFooter>
                  <AlertDialogCancel disabled={!!processing}>Cancel</AlertDialogCancel>
                  <AlertDialogAction
                     className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                     disabled={!!processing}
                     onClick={() => void confirmApprove()}
                  >
                     Delete organism
                  </AlertDialogAction>
               </AlertDialogFooter>
            </AlertDialogContent>
         </AlertDialog>
      </>
   )
}
