// front/components/cms/dashboard/record-models-module.tsx
'use client'

import { ArrowRight, Dna, FlaskConical, FolderOpen, ListOrdered, Loader2, Plus, type LucideIcon } from 'lucide-react'
import Link from 'next/link'
import { useCallback, useEffect, useMemo, useState } from 'react'

import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import {
   Table,
   TableBody,
   TableCell,
   TableHead,
   TableHeader,
   TableRow,
} from '@/components/ui/table'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import type { DataModels } from '@/lib/portal/types'
import type { PortalStatRow } from '@/lib/portal/taxonNodeStats'
import { cmsGetItems, cmsGetUserSamples } from '@/lib/cms/services/auth'
import { useCmsAuthStore } from '@/stores/cms-auth-store'
import { useCmsDrawerStore } from '@/stores/cms-drawer-store'

const LIMIT = 5

type TabMeta = {
   label: string
   icon: LucideIcon
   columns: string[]
   createLabel?: string
}

const TAB_META: Record<string, Omit<TabMeta, never>> = {
   biosamples: {
      label: 'Biosamples',
      icon: FlaskConical,
      columns: ['accession', 'scientific_name'],
      createLabel: 'Import biosample',
   },
   reads: {
      label: 'Reads',
      icon: FolderOpen,
      columns: ['run_accession', 'scientific_name'],
      createLabel: 'Import reads',
   },
   assemblies: {
      label: 'Assemblies',
      icon: Dna,
      columns: ['accession', 'assembly_name', 'scientific_name'],
      createLabel: 'Import assembly',
   },
   local_samples: {
      label: 'Local samples',
      icon: FlaskConical,
      columns: ['sample_id', 'scientific_name'],
      createLabel: 'Import samples',
   },
   annotations: {
      label: 'Annotations',
      icon: ListOrdered,
      columns: ['name', 'scientific_name'],
      createLabel: 'Create annotation',
   },
}

function cellValue(row: Record<string, unknown>, col: string): string {
   const val = row[col] ?? (row.metadata as Record<string, unknown> | undefined)?.[col]
   if (val === undefined || val === null) return '—'
   if (Array.isArray(val)) return val.join(', ')
   return String(val)
}

export function RecordModelsModule({ stats }: { stats: PortalStatRow[] }) {
   const userName = useCmsAuthStore((s) => s.userName)
   const isAdmin = useCmsAuthStore((s) => s.userRole === 'Admin')
   const openDrawer = useCmsDrawerStore((s) => s.open)

   const tabs = useMemo(() => {
      return stats
         .filter(({ key }) => key in TAB_META && key !== 'organisms')
         .map(({ key, count }) => ({
            key,
            count,
            ...TAB_META[key],
         }))
   }, [stats])

   const [activeTab, setActiveTab] = useState<DataModels | ''>('')
   const [items, setItems] = useState<Record<string, unknown>[]>([])
   const [total, setTotal] = useState(0)
   const [loading, setLoading] = useState(false)
   const [page, setPage] = useState(1)

   useEffect(() => {
      const first = tabs[0]?.key
      if (first && (!activeTab || !tabs.some((t) => t.key === activeTab))) {
         setActiveTab(first)
         setPage(1)
      }
   }, [tabs, activeTab])

   const fetchTabData = useCallback(async () => {
      if (!activeTab) return
      setLoading(true)
      try {
         const params = { limit: LIMIT, offset: (page - 1) * LIMIT }
         if (activeTab === 'local_samples' && !isAdmin && userName) {
            const body = await cmsGetUserSamples(userName, params)
            setItems(body.data ?? [])
            setTotal(body.total ?? 0)
         } else {
            const body = await cmsGetItems(activeTab as DataModels, params)
            setItems(body.data ?? [])
            setTotal(body.total ?? 0)
         }
      } catch {
         setItems([])
         setTotal(0)
      } finally {
         setLoading(false)
      }
   }, [activeTab, isAdmin, userName, page])

   useEffect(() => {
      void fetchTabData()
   }, [fetchTabData])

   function openCreateForTab(key: DataModels) {
      if (key === 'biosamples') openDrawer({ panel: 'insdc', insdcImportModel: 'biosamples' })
      else if (key === 'reads') openDrawer({ panel: 'insdc', insdcImportModel: 'reads' })
      else if (key === 'assemblies') openDrawer({ panel: 'insdc', insdcImportModel: 'assemblies' })
      else if (key === 'local_samples') openDrawer({ panel: 'spreadsheet' })
      else if (key === 'annotations') openDrawer({ panel: 'annotation' })
   }

   if (tabs.length === 0) return null

   return (
      <Card className="border-border/80 shadow-sm">
         <CardHeader>
            <CardTitle>{isAdmin ? 'Data records' : 'My data records'}</CardTitle>
            <CardDescription>Browse records by type. Use a tab to switch models.</CardDescription>
         </CardHeader>
         <CardContent className="space-y-4">
            <Tabs
               value={activeTab || tabs[0].key}
               onValueChange={(v) => {
                  setActiveTab(v as DataModels)
                  setPage(1)
               }}
            >
               <TabsList className="flex h-auto w-full flex-wrap justify-start gap-1 bg-muted/50 p-1">
                  {tabs.map((tab) => {
                     const Icon = tab.icon
                     return (
                        <TabsTrigger
                           key={tab.key}
                           value={tab.key}
                           className="gap-1.5 px-2 py-1.5 text-xs sm:text-sm"
                        >
                           <Icon className="h-3.5 w-3.5 shrink-0 opacity-70" />
                           <span className="hidden sm:inline">{tab.label}</span>
                           <span className="rounded-full bg-background/80 px-1.5 py-0 text-[10px] font-semibold tabular-nums sm:text-xs">
                              {tab.count}
                           </span>
                        </TabsTrigger>
                     )
                  })}
               </TabsList>

               {tabs.map((tab) => (
                  <TabsContent key={tab.key} value={tab.key} className="mt-4 space-y-4">
                     {loading && activeTab === tab.key ? (
                        <div className="flex justify-center py-12 text-muted-foreground">
                           <Loader2 className="h-8 w-8 animate-spin" />
                        </div>
                     ) : items.length === 0 && activeTab === tab.key ? (
                        <div className="flex flex-col items-center gap-3 rounded-lg border border-dashed border-border py-10 text-center">
                           <tab.icon className="h-10 w-10 text-muted-foreground/50" />
                           <p className="text-sm text-muted-foreground">No {tab.label.toLowerCase()} yet.</p>
                           {tab.createLabel ? (
                              <Button size="sm" className="gap-2" onClick={() => openCreateForTab(tab.key)}>
                                 <Plus className="h-4 w-4" />
                                 {tab.createLabel}
                              </Button>
                           ) : null}
                        </div>
                     ) : activeTab === tab.key ? (
                        <>
                           <div className="rounded-md border border-border">
                              <Table>
                                 <TableHeader>
                                    <TableRow>
                                       {tab.columns.map((col) => (
                                          <TableHead key={col} className="capitalize">
                                             {col.split('_').join(' ')}
                                          </TableHead>
                                       ))}
                                       <TableHead className="text-right">Actions</TableHead>
                                    </TableRow>
                                 </TableHeader>
                                 <TableBody>
                                    {items.map((row, i) => (
                                       <TableRow key={i}>
                                          {tab.columns.map((col) => (
                                             <TableCell key={col} className="max-w-[200px] truncate font-mono text-sm">
                                                {cellValue(row, col)}
                                             </TableCell>
                                          ))}
                                          <TableCell className="text-right">
                                             <Button variant="ghost" size="sm" className="gap-1" asChild>
                                                <Link href="/admin">
                                                   Open dashboard
                                                   <ArrowRight className="h-3.5 w-3.5" />
                                                </Link>
                                             </Button>
                                          </TableCell>
                                       </TableRow>
                                    ))}
                                 </TableBody>
                              </Table>
                           </div>
                           {total > LIMIT ? (
                              <div className="flex items-center justify-between text-sm text-muted-foreground">
                                 <span>
                                    Page {page} / {Math.ceil(total / LIMIT)}
                                 </span>
                                 <div className="flex gap-2">
                                    <Button
                                       variant="outline"
                                       size="sm"
                                       disabled={page <= 1}
                                       onClick={() => setPage((p) => p - 1)}
                                    >
                                       Previous
                                    </Button>
                                    <Button
                                       variant="outline"
                                       size="sm"
                                       disabled={page >= Math.ceil(total / LIMIT)}
                                       onClick={() => setPage((p) => p + 1)}
                                    >
                                       Next
                                    </Button>
                                 </div>
                              </div>
                           ) : null}
                        </>
                     ) : null}
                  </TabsContent>
               ))}
            </Tabs>
         </CardContent>
      </Card>
   )
}

// biogenome-client/src/components/cms/dashboard/RecordModelsModule.vue
<template>
   <section aria-labelledby="records-module-title">
      <CmsCard
         :title="isAdmin ? 'Data Records' : 'My Data Records'"
         description="Browse and manage your data records by type. Click a tab to explore that model."
         icon="fa-database"
         color="purple"
         :loading="isLoading"
      >
         <!-- Tab bar lives in the filters slot so it's visually inside the card -->
         <template #filters>
            <div class="cms-tabs" role="tablist" aria-label="Data model tabs">
               <button
                  v-for="tab in tabs"
                  :key="tab.key"
                  role="tab"
                  :aria-selected="activeTab === tab.key"
                  :class="['cms-tabs__tab', { 'cms-tabs__tab--active': activeTab === tab.key }]"
                  @click="selectTab(tab.key)"
               >
                  <CmsIcon :name="tab.icon" size="0.75rem" class="cms-tabs__icon" />
                  <span>{{ tab.label }}</span>
                  <span class="cms-tabs__count" :class="{ 'cms-tabs__count--active': activeTab === tab.key }">
                     {{ tab.count }}
                  </span>
               </button>
            </div>
         </template>

         <!-- Records table / empty state -->
         <template v-if="!isLoading">
            <DashboardEmptyState
               v-if="items.length === 0"
               :icon="activeTabDef?.icon ?? 'fa-box-open'"
               :title="`No ${activeTabDef?.label ?? 'records'} yet`"
               description="Nothing has been imported or created for this model yet."
            >
               <template v-if="activeTabDef?.createLabel" #actions>
                  <CmsBtn icon="fa-plus" variant="primary" @click="openCreateForActiveTab">
                     {{ activeTabDef.createLabel }}
                  </CmsBtn>
               </template>
            </DashboardEmptyState>

            <table v-else class="cms-table" role="grid">
               <thead>
                  <tr class="cms-table__head-row">
                     <th
                        v-for="col in activeTabDef?.columns ?? []"
                        :key="col"
                        class="cms-table__th"
                     >
                        {{ col.split('_').join(' ') }}
                     </th>
                     <th class="cms-table__th cms-table__th--right">Actions</th>
                  </tr>
               </thead>
               <tbody>
                  <tr v-for="(row, i) in items" :key="i" class="cms-table__row">
                     <td
                        v-for="col in activeTabDef?.columns ?? []"
                        :key="col"
                        class="cms-table__td cms-table__td--truncated"
                     >
                        {{ cellValue(row, col) }}
                     </td>
                     <td class="cms-table__td cms-table__td--right">
                        <router-link
                           :to="{ name: 'admin' }"
                           class="cms-link-btn"
                        >
                           Open dashboard
                           <CmsIcon name="fa-arrow-right" size="0.65rem" />
                        </router-link>
                     </td>
                  </tr>
               </tbody>
            </table>
         </template>

         <!-- Pagination -->
         <template v-if="!isLoading && total > limit" #footer>
            <CmsPagination
               v-model="currentPage"
               :total="total"
               :page-size="limit"
               @update:model-value="fetchTabData"
            />
         </template>
      </CmsCard>
   </section>
</template>

<script setup lang="ts">
   import { computed, onMounted, ref, watch } from 'vue'
   import { useGlobalStore } from '../../../stores/global-store'
   import ItemService from '../../../services/CommonService'
   import AuthService from '../../../services/AuthService'
   import type { DataModels } from '../../../data/types'
   import { iconMap } from '../../../composable/useIconMap'
   import CmsCard from './CmsCard.vue'
   import CmsIcon from '../ui/CmsIcon.vue'
   import CmsBtn from '../ui/CmsBtn.vue'
   import CmsPagination from './CmsPagination.vue'
   import DashboardEmptyState from './DashboardEmptyState.vue'
   import { useCmsDashboardDrawerStore } from '../../../stores/cms-dashboard-drawer-store'

   const props = defineProps<{
      stats: { key: DataModels; count: number }[]
   }>()

   const globalStore = useGlobalStore()
   const drawer = useCmsDashboardDrawerStore()
   const isAdmin = computed(() => globalStore.userRole === 'Admin')

   function openCreateForActiveTab() {
      const k = activeTab.value
      if (k === 'biosamples') drawer.open({ panel: 'insdc', insdcImportModel: 'biosamples' })
      else if (k === 'reads') drawer.open({ panel: 'insdc', insdcImportModel: 'reads' })
      else if (k === 'assemblies') drawer.open({ panel: 'insdc', insdcImportModel: 'assemblies' })
      else if (k === 'local_samples') drawer.open({ panel: 'spreadsheet' })
      else if (k === 'annotations') drawer.open({ panel: 'annotation' })
   }

   type TabDef = {
      key: DataModels
      label: string
      icon: string
      count: number
      columns: string[]
      createLabel?: string
   }

   const tabMeta: Record<string, Omit<TabDef, 'key' | 'count'>> = {
      biosamples: {
         label: 'Biosamples',
         icon: 'fa-vial',
         columns: ['accession', 'scientific_name'],
         createLabel: 'Import Biosample',
      },
      reads: {
         label: 'Reads',
         icon: 'fa-folder',
         columns: ['run_accession', 'scientific_name'],
         createLabel: 'Import Reads',
      },
      assemblies: {
         label: 'Assemblies',
         icon: 'fa-dna',
         columns: ['accession', 'assembly_name', 'scientific_name'],
         createLabel: 'Import Assembly',
      },
      local_samples: {
         label: 'Local Samples',
         icon: 'fa-flask',
         columns: ['sample_id', 'scientific_name'],
         createLabel: 'Import Samples',
      },
      annotations: {
         label: 'Annotations',
         icon: 'fa-bars-staggered',
         columns: ['name', 'scientific_name'],
         createLabel: 'Create Annotation',
      },
   }

   const tabs = computed<TabDef[]>(() =>
      props.stats
         .filter(({ key }) => key in tabMeta && key !== 'organisms')
         .map(({ key, count }) => ({ key, count, ...tabMeta[key] })),
   )

   const activeTab = ref<DataModels>(tabs.value[0]?.key ?? 'biosamples')
   const activeTabDef = computed(() => tabs.value.find((t) => t.key === activeTab.value))

   const items = ref<Record<string, any>[]>([])
   const total = ref(0)
   const isLoading = ref(false)
   const currentPage = ref(1)
   const limit = 5

   function cellValue(row: Record<string, any>, col: string) {
      const val = row[col] ?? row.metadata?.[col] ?? '—'
      if (Array.isArray(val)) return val.join(', ')
      return val
   }

   async function fetchTabData() {
      if (!activeTab.value) return
      isLoading.value = true
      try {
         const params = { limit, offset: (currentPage.value - 1) * limit }
         if (activeTab.value === 'local_samples' && !isAdmin.value) {
            const { data } = await AuthService.getUserSamples(globalStore.userName, params)
            items.value = data.data ?? []
            total.value = data.total ?? 0
         } else {
            const { data } = await ItemService.getItems(activeTab.value, params)
            items.value = data.data ?? []
            total.value = data.total ?? 0
         }
      } catch {
         items.value = []
         total.value = 0
      } finally {
         isLoading.value = false
      }
   }

   function selectTab(key: DataModels) {
      activeTab.value = key
      currentPage.value = 1
   }

   watch(activeTab, fetchTabData)

   onMounted(() => {
      if (tabs.value.length) {
         const firstKey = tabs.value[0].key
         if (activeTab.value === firstKey) {
            fetchTabData()
         } else {
            activeTab.value = firstKey
         }
      }
   })
</script>
