// front/components/cms/dashboard/submitted-biosamples-module.tsx
'use client'

import Link from 'next/link'
import { useCallback, useEffect, useState } from 'react'
import { FlaskConical, Loader2, Plus } from 'lucide-react'

import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import {
   Table,
   TableBody,
   TableCell,
   TableHead,
   TableHeader,
   TableRow,
} from '@/components/ui/table'
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group'
import { DashboardModuleHeader } from '@/components/cms/dashboard/dashboard-module-header'
import { DashboardModulePagination } from '@/components/cms/dashboard/dashboard-module-pagination'
import { SubmittedBiosampleDetailDialog } from '@/components/cms/dashboard/submitted-biosample-detail-dialog'
import { cmsGetSubmittedBioSamples } from '@/lib/cms/services/auth'
import { cn } from '@/lib/utils'
import { useCmsAuthStore } from '@/stores/cms-auth-store'

const LIMIT = 6

export function SubmittedBiosamplesModule({ hasEnaTemplate }: { hasEnaTemplate: boolean }) {
   const userName = useCmsAuthStore((s) => s.userName)
   const isAdmin = useCmsAuthStore((s) => s.userRole === 'Admin')

   const [items, setItems] = useState<Record<string, unknown>[]>([])
   const [total, setTotal] = useState(0)
   const [loading, setLoading] = useState(true)
   const [filterDraft, setFilterDraft] = useState('')
   const [filter, setFilter] = useState('')
   const [page, setPage] = useState(1)
   const [viewMode, setViewMode] = useState<'filtered' | 'all'>(isAdmin ? 'all' : 'filtered')
   const [detailAccession, setDetailAccession] = useState<string | null>(null)

   useEffect(() => {
      const t = setTimeout(() => {
         setFilter(filterDraft)
         setPage(1)
      }, 350)
      return () => clearTimeout(t)
   }, [filterDraft])

   const fetchData = useCallback(async () => {
      setLoading(true)
      try {
         const query: Record<string, string | number> = {
            filter,
            limit: LIMIT,
            offset: (page - 1) * LIMIT,
         }
         if (!isAdmin || viewMode === 'filtered') query.user = userName
         const { data, total: t } = await cmsGetSubmittedBioSamples(query)
         setItems(data ?? [])
         setTotal(t ?? 0)
      } catch {
         setItems([])
         setTotal(0)
      } finally {
         setLoading(false)
      }
   }, [isAdmin, userName, filter, page, viewMode])

   useEffect(() => {
      void fetchData()
   }, [fetchData])

   return (
      <Card className="gap-3 border-border/80 shadow-sm">
         <DashboardModuleHeader
            description={
               isAdmin
                  ? 'All biosamples submitted to EBI across curators. Use Mine / All to change scope.'
                  : 'Biosamples you have submitted to EBI BioSamples.'
            }
            action={
               hasEnaTemplate ? (
                  <Button size="sm" asChild className="gap-2">
                     <Link href="/admin/publish-biosample">
                        <Plus className="h-4 w-4" />
                        Submit
                     </Link>
                  </Button>
               ) : null
            }
         />
         <CardContent className="space-y-4">
            <div className="flex flex-col gap-3 sm:flex-row sm:flex-wrap sm:items-center">
               <Input
                  placeholder="Filter by name or accession…"
                  value={filterDraft}
                  onChange={(e) => setFilterDraft(e.target.value)}
                  className="max-w-md"
               />
               {isAdmin ? (
                  <ToggleGroup
                     type="single"
                     value={viewMode}
                     onValueChange={(v) => {
                        if (v === 'filtered' || v === 'all') {
                           setViewMode(v)
                           setPage(1)
                        }
                     }}
                  >
                     <ToggleGroupItem value="filtered">Mine</ToggleGroupItem>
                     <ToggleGroupItem value="all">All</ToggleGroupItem>
                  </ToggleGroup>
               ) : null}
            </div>
            {loading ? (
               <div className="flex justify-center py-10 text-muted-foreground">
                  <Loader2 className="h-8 w-8 animate-spin" />
               </div>
            ) : items.length === 0 ? (
               <div className="flex flex-col items-center gap-3 py-10 text-center text-muted-foreground">
                  <FlaskConical className="h-10 w-10 opacity-40" />
                  <p className="text-sm">No biosamples found.</p>
                  {hasEnaTemplate ? (
                     <Button size="sm" asChild>
                        <Link href="/admin/publish-biosample">Submit biosample</Link>
                     </Button>
                  ) : null}
               </div>
            ) : (
               <div className="rounded-md border border-border">
                  <Table>
                     <TableHeader>
                        <TableRow>
                           <TableHead>Species</TableHead>
                           <TableHead>Sample</TableHead>
                           <TableHead>Accession</TableHead>
                           {isAdmin ? <TableHead>Submitted by</TableHead> : null}
                        </TableRow>
                     </TableHeader>
                     <TableBody>
                        {items.map((item) => {
                           const acc = item.accession != null ? String(item.accession) : ''
                           return (
                              <TableRow
                                 key={String(item.accession ?? item.name)}
                                 className={cn(acc && 'cursor-pointer hover:bg-muted/50')}
                                 tabIndex={acc ? 0 : undefined}
                                 aria-label={acc ? `View details for biosample ${acc}` : undefined}
                                 onClick={() => {
                                    if (acc) setDetailAccession(acc)
                                 }}
                                 onKeyDown={(e) => {
                                    if (!acc) return
                                    if (e.key === 'Enter' || e.key === ' ') {
                                       e.preventDefault()
                                       setDetailAccession(acc)
                                    }
                                 }}
                              >
                              <TableCell className="italic">
                                 {String(item.scientific_name ?? '—')}
                              </TableCell>
                              <TableCell className="font-mono text-sm">
                                 {String(item.name ?? '—')}
                              </TableCell>
                              <TableCell>
                                 {item.accession ? (
                                    <a
                                       href={`https://www.ebi.ac.uk/biosamples/samples/${item.accession}`}
                                       target="_blank"
                                       rel="noreferrer"
                                       className="text-primary underline-offset-4 hover:underline"
                                       onClick={(e) => e.stopPropagation()}
                                    >
                                       {String(item.accession)}
                                    </a>
                                 ) : (
                                    '—'
                                 )}
                              </TableCell>
                              {isAdmin ? (
                                 <TableCell className="text-muted-foreground">
                                    {String(item.user ?? '—')}
                                 </TableCell>
                              ) : null}
                           </TableRow>
                           )
                        })}
                     </TableBody>
                  </Table>
               </div>
            )}
            {total > LIMIT ? (
               <DashboardModulePagination
                  page={page}
                  totalPages={Math.ceil(total / LIMIT)}
                  onPrevious={() => setPage((p) => p - 1)}
                  onNext={() => setPage((p) => p + 1)}
               />
            ) : null}
         </CardContent>
         <SubmittedBiosampleDetailDialog
            accession={detailAccession}
            open={detailAccession != null}
            onOpenChange={(o) => {
               if (!o) setDetailAccession(null)
            }}
         />
      </Card>
   )
}

// biogenome-client/src/components/cms/dashboard/SubmittedBiosamplesModule.vue
<template>
   <section aria-labelledby="biosamples-module-title">
      <CmsCard
         :title="isAdmin ? 'Submitted Biosamples' : 'My EBI Biosamples'"
         :description="isAdmin
            ? 'All biosamples submitted to EBI across all curators.'
            : 'Biosamples you have submitted to EBI BioSamples.'"
         icon="fa-vial"
         color="teal"
         :loading="isLoading"
      >
         <!-- Header actions -->
         <template v-if="hasENATemplate" #actions>
            <CmsBtn :to="{ name: 'publish-biosample' }" icon="fa-plus" variant="primary">
               Submit Biosample
            </CmsBtn>
         </template>

         <!-- Filters -->
         <template #filters>
            <CmsSearchInput
               v-model="filter"
               field-name="cms-submitted-biosamples-filter"
               placeholder="Filter by name or accession…"
               @update:model-value="debouncedFetch"
            />
            <div v-if="isAdmin" class="cms-toggle-group">
               <button
                  v-for="opt in viewOptions"
                  :key="opt.value"
                  class="cms-toggle-group__btn"
                  :class="{ 'cms-toggle-group__btn--active': viewMode === opt.value }"
                  @click="setViewMode(opt.value as typeof viewMode)"
               >
                  {{ opt.label }}
               </button>
            </div>
         </template>

         <!-- Table -->
         <template v-if="!isLoading">
            <DashboardEmptyState
               v-if="items.length === 0"
               icon="fa-vial"
               title="No biosamples found"
               description="No submitted biosamples match your current filters."
            >
               <template v-if="hasENATemplate" #actions>
                  <CmsBtn :to="{ name: 'publish-biosample' }" icon="fa-plus" variant="primary">
                     Submit Biosample
                  </CmsBtn>
               </template>
            </DashboardEmptyState>

            <table v-else class="cms-table" role="grid">
               <thead>
                  <tr class="cms-table__head-row">
                     <th class="cms-table__th">Species</th>
                     <th class="cms-table__th">Sample name</th>
                     <th class="cms-table__th">Accession</th>
                     <th v-if="isAdmin" class="cms-table__th">Submitted by</th>
                  </tr>
               </thead>
               <tbody>
                  <tr
                     v-for="item in items"
                     :key="item.accession ?? item.name"
                     class="cms-table__row"
                  >
                     <td class="cms-table__td">
                        <span class="cms-table__sci-name">{{ item.scientific_name ?? '—' }}</span>
                     </td>
                     <td class="cms-table__td cms-table__td--mono">{{ item.name ?? '—' }}</td>
                     <td class="cms-table__td">
                        <router-link
                           v-if="item.accession"
                           :to="{ name: 'item', params: { model: 'biosamples', id: item.accession } }"
                           class="cms-accession-link"
                        >
                           {{ item.accession }}
                        </router-link>
                        <span v-else class="cms-table__muted">—</span>
                     </td>
                     <td v-if="isAdmin" class="cms-table__td">
                        <span class="cms-table__muted">{{ item.user ?? '—' }}</span>
                     </td>
                  </tr>
               </tbody>
            </table>
         </template>

         <!-- Pagination footer -->
         <template v-if="!isLoading && total > limit" #footer>
            <CmsPagination
               v-model="currentPage"
               :total="total"
               :page-size="limit"
               @update:model-value="fetchData"
            />
         </template>
      </CmsCard>
   </section>
</template>

<script setup lang="ts">
   import { computed, inject, onMounted, ref, watch } from 'vue'
   import { useGlobalStore } from '../../../stores/global-store'
   import EBIService from '../../../services/EBIService'
   import type { AppConfig } from '../../../data/types'
   import CmsCard from './CmsCard.vue'
   import CmsBtn from '../ui/CmsBtn.vue'
   import CmsSearchInput from './CmsSearchInput.vue'
   import CmsPagination from './CmsPagination.vue'
   import DashboardEmptyState from './DashboardEmptyState.vue'

   const globalStore = useGlobalStore()
   const configs = inject('appConfig') as AppConfig
   const isAdmin = computed(() => globalStore.userRole === 'Admin')
   const hasENATemplate = computed(() => configs?.general?.enaTemplate)

   const items = ref<Record<string, any>[]>([])
   const total = ref(0)
   const isLoading = ref(false)
   const filter = ref('')
   const currentPage = ref(1)
   const limit = 6
   const viewMode = ref<'filtered' | 'all'>(isAdmin.value ? 'all' : 'filtered')

   const viewOptions = [
      { label: 'My Biosamples', value: 'filtered' },
      { label: 'All Biosamples', value: 'all' },
   ]

   function debounce<T extends (...args: any[]) => void>(fn: T, ms = 350) {
      let timer: ReturnType<typeof setTimeout>
      return (...args: Parameters<T>) => {
         clearTimeout(timer)
         timer = setTimeout(() => fn(...args), ms)
      }
   }

   function setViewMode(val: 'filtered' | 'all') {
      viewMode.value = val
   }

   async function fetchData() {
      isLoading.value = true
      try {
         const query: Record<string, any> = {
            filter: filter.value,
            limit,
            offset: (currentPage.value - 1) * limit,
         }
         if (!isAdmin.value || viewMode.value === 'filtered') {
            query.user = globalStore.userName
         }
         const { data } = await EBIService.getSubmittedBioSamples(query)
         items.value = data.data ?? []
         total.value = data.total ?? 0
      } catch {
         items.value = []
      } finally {
         isLoading.value = false
      }
   }

   const debouncedFetch = debounce(() => {
      currentPage.value = 1
      fetchData()
   })

   watch(viewMode, () => {
      currentPage.value = 1
      fetchData()
   })

   onMounted(fetchData)
</script>
